### ISSUE TITLE
Wrong formatting when generating settings file when using root_path in app_config.yml

### ISSUE THREAD

**Issue by brlanier** [amco/biran#35]
On legacy apps that we are migrating, found this "issue" when putting `vhost` in the settings block and then trying to generate the settings.yml file in development using `root_path` instead of `base_path`:

Dump of @app_config shows the following when using root_path:
```
:app_root_dir=>#<Pathname:/Users/brian/repos/x4>, 
:app_shared_dir=>#<Pathname:/Users/brian/repos/x4>, 
:app_base_dir=>#<Pathname:/Users/brian/repos/x4>
```

And output in config/settings.yml looks like:
```
  vhost:
    public_dir: "/Users/brian/repos/x4/public"
    shared_dir: !ruby/object:Pathname
      path: "/Users/brian/repos/x4"
    log_dir: "/Users/brian/repos/x4/log"
```
When they should match the output when using base_path:
```
:app_root_dir=>"/Users/brian/repos/x4", 
:app_shared_dir=>"/Users/brian/repos/x4", 
:app_base_dir=>"/Users/brian/repos/x4",
```
and vhost looks like:
```
  vhost:
    public_dir: "/Users/brian/repos/x4/public"
    shared_dir: "/Users/brian/repos/x4"
    log_dir: "/Users/brian/repos/x4/log"
```
The difference being one looks to be a string and the other a path object.
Not sure if this is something worth fixing but would like to look into it
