### ISSUE TITLE
Biran cannot create files with same name in different locations

### ISSUE THREAD

**Issue by brlanier** [amco/biran#45]
There is a need to create two files with the same name, yet in different output dirs. Currently, we pull the file name from the yaml block and assume the template name and the file name from that "label".
For instance, with the following block:
```
    files_to_generate:
      couchdb:
        extension: '.yml'
```
Biran will build a file at `config/couchdb.yml` from a template named `config/_couchdb.yml.erb`.
If we have a block that looks like:
```
    files_to_generate:
      couchdb:
        extension: '.yml'
        output_dir: '<%= File.join('bin', 'service', 'config') %>'
```
Biran would build a file at `bin/service/config/couchdb.yml` from a template named `config/_couchdb.yml.erb`
Both of those are great and working. But what if you need both in the same app. Only one would run based on those blocks also generating rake tasks and overriding the previously defined task.
Add to that the need to possibly have different erb templates for the two different files of the same name.
